export type Requirement = { id: string; uat: string; status: string; statement: string };

export const requirements: Requirement[] = [
  { id: "REQ-FD-001-01", uat: "UAT-FD-001-01", status: "in product", statement: `Given an authorized receptionist and an active hotel/clinic context, when the dashboard loads` },
  { id: "REQ-FD-001-02", uat: "UAT-FD-001-02", status: "in product", statement: `Given a user searches by name, room, passport/ID or phone` },
  { id: "REQ-FD-001-03", uat: "UAT-FD-001-03", status: "in product", statement: `Given an active encounter is selected, when Send to Triage is used` },
  { id: "REQ-FD-001-04", uat: "UAT-FD-001-04", status: "in product", statement: `Given a room visit is requested` },
  { id: "REQ-FD-002-01", uat: "UAT-FD-002-01", status: "in product", statement: `Given all required registration fields are valid, when the receptionist completes Review & Save` },
  { id: "REQ-FD-002-02", uat: "UAT-FD-002-02", status: "in product", statement: `Given a probable existing patient is detected, when the user attempts to save` },
  { id: "REQ-FD-002-03", uat: "UAT-FD-002-03", status: "in product", statement: `Given an optional insurance provider is selected` },
  { id: "REQ-FD-002-04", uat: "UAT-FD-002-04", status: "in product", statement: `Given a returning patient starts a new visit` },
  { id: "REQ-FD-003-01", uat: "UAT-FD-003-01", status: "in product", statement: `Given a patient exists and the user searches using supported identity data` },
  { id: "REQ-FD-003-02", uat: "UAT-FD-003-02", status: "in product", statement: `Given several possible matches exist` },
  { id: "REQ-FD-003-03", uat: "UAT-FD-003-03", status: "in product", statement: `Given an existing patient is selected and Start New Visit is confirmed` },
  { id: "REQ-FD-004-01", uat: "UAT-FD-004-01", status: "in product", statement: `Given active encounters exist for the selected clinic` },
  { id: "REQ-FD-004-02", uat: "UAT-FD-004-02", status: "in product", statement: `Given a valid status transition is performed` },
  { id: "REQ-FD-004-03", uat: "UAT-FD-004-03", status: "in product", statement: `Given an encounter is sent to triage` },
  { id: "REQ-CLN-001-01", uat: "UAT-CLN-001-01", status: "in product", statement: `Given an encounter is In Triage, when an authorized nurse opens it` },
  { id: "REQ-CLN-001-02", uat: "UAT-CLN-001-02", status: "in product", statement: `Given vitals and triage category are recorded, when Send to Doctor is selected` },
  { id: "REQ-CLN-001-03", uat: "UAT-CLN-001-03", status: "in product", statement: `Given Emergency is selected` },
  { id: "REQ-CLN-001-04", uat: "UAT-CLN-001-04", status: "in product", statement: `Given the doctor opens the encounter` },
  { id: "REQ-CLN-002-01", uat: "UAT-CLN-002-01", status: "in product", statement: `Given a patient with prior visits / When the clinician opens EMR` },
  { id: "REQ-CLN-002-02", uat: "UAT-CLN-002-02", status: "in product", statement: `Given an allergy is documented / When the EMR opens` },
  { id: "REQ-CLN-002-03", uat: "UAT-CLN-002-03", status: "in product", statement: `Given a signed prior encounter / When a user attempts to edit it` },
  { id: "REQ-CLN-002-04", uat: "UAT-CLN-002-04", status: "in product", statement: `Given a non-clinical user / When accessing EMR` },
  { id: "REQ-CLN-003-01", uat: "UAT-CLN-003-01", status: "in product", statement: `Given a triaged encounter / When the doctor opens it` },
  { id: "REQ-CLN-003-02", uat: "UAT-CLN-003-02", status: "in product", statement: `Given required clinical fields are incomplete / When doctor selects final completion` },
  { id: "REQ-CLN-003-03", uat: "UAT-CLN-003-03", status: "in product", statement: `Given the encounter is saved as draft / When reopened by the same/authorized doctor` },
  { id: "REQ-CLN-003-04", uat: "UAT-CLN-003-04", status: "in product", statement: `Given a signed encounter / When a change is required` },
  { id: "REQ-CLN-004-01", uat: "UAT-CLN-004-01", status: "in product", statement: `Given a selected coded diagnosis / When saved` },
  { id: "REQ-CLN-004-02", uat: "UAT-CLN-004-02", status: "in product", statement: `Given referral is required / When plan is finalized` },
  { id: "REQ-CLN-004-03", uat: "UAT-CLN-004-03", status: "in product", statement: `Given the encounter has no primary diagnosis / When final completion is attempted` },
  { id: "REQ-CLN-004-04", uat: "UAT-CLN-004-04", status: "in product", statement: `Given a coding reviewer views the case` },
  { id: "REQ-CLN-005-01", uat: "UAT-CLN-005-01", status: "in product", statement: `Given an active encounter / When doctor adds a medication` },
  { id: "REQ-CLN-005-02", uat: "UAT-CLN-005-02", status: "in product", statement: `Given a documented allergy conflict / When medication is selected` },
  { id: "REQ-CLN-005-03", uat: "UAT-CLN-005-03", status: "in product", statement: `Given all mandatory Rx data is complete / When doctor signs` },
  { id: "REQ-CLN-005-04", uat: "UAT-CLN-005-04", status: "in product", statement: `Given an issued prescription / When pharmacist opens it` },
  { id: "REQ-CLN-006-01", uat: "UAT-CLN-006-01", status: "in product", statement: `Given no investigation selected / When Submit is clicked` },
  { id: "REQ-CLN-006-02", uat: "UAT-CLN-006-02", status: "in product", statement: `Given contrast imaging is selected / When safety data is incomplete` },
  { id: "REQ-CLN-006-03", uat: "UAT-CLN-006-03", status: "in product", statement: `Given a critical result / When recorded` },
  { id: "REQ-CLN-006-04", uat: "UAT-CLN-006-04", status: "in product", statement: `Given a final result / When clinician reviews it` },
  { id: "REQ-CLN-007-01", uat: "UAT-CLN-007-01", status: "in product", statement: `Given a completed encounter / When Generate Report is selected` },
  { id: "REQ-CLN-007-02", uat: "UAT-CLN-007-02", status: "in product", statement: `Given a draft report / When doctor signs` },
  { id: "REQ-CLN-007-03", uat: "UAT-CLN-007-03", status: "in product", statement: `Given a final report / When an edit is required` },
  { id: "REQ-CLN-007-04", uat: "UAT-CLN-007-04", status: "in product", statement: `Given a report is shared externally / When distribution completes` },
  { id: "REQ-CLN-008-01", uat: "UAT-CLN-008-01", status: "in product", statement: `Given an active encounter / When Add Progress Note is selected` },
  { id: "REQ-CLN-008-02", uat: "UAT-CLN-008-02", status: "in product", statement: `Given a signed note / When an edit is attempted` },
  { id: "REQ-CLN-008-03", uat: "UAT-CLN-008-03", status: "in product", statement: `Given follow-up is required / When a due date is saved` },
  { id: "REQ-CLN-008-04", uat: "UAT-CLN-008-04", status: "in product", statement: `Given episode closure / When a new independent visit later occurs` },
  { id: "REQ-PHM-001-01", uat: "UAT-PHM-001-01", status: "in product", statement: `Given stock exists in multiple batches / When dashboard loads` },
  { id: "REQ-PHM-001-02", uat: "UAT-PHM-001-02", status: "in product", statement: `Given a pharmacist searches an active patient/order / When a valid match is selected` },
  { id: "REQ-PHM-001-03", uat: "UAT-PHM-001-03", status: "in product", statement: `Given insufficient stock / When dispense is attempted` },
  { id: "REQ-PHM-001-04", uat: "UAT-PHM-001-04", status: "in product", statement: `Given location A is selected / When KPIs load` },
  { id: "REQ-PHM-002-01", uat: "UAT-PHM-002-01", status: "in product", statement: `Given a valid prescription and sufficient eligible stock / When pharmacist confirms dispense` },
  { id: "REQ-PHM-002-02", uat: "UAT-PHM-002-02", status: "in product", statement: `Given an expired batch / When selected` },
  { id: "REQ-PHM-002-03", uat: "UAT-PHM-002-03", status: "in product", statement: `Given partial quantity is dispensed / When confirmation succeeds` },
  { id: "REQ-PHM-002-04", uat: "UAT-PHM-002-04", status: "in product", statement: `Given the user retries after a timeout / When the same dispense request is resubmitted` },
  { id: "REQ-INV-001-01", uat: "UAT-INV-001-01", status: "in product", statement: `Given a tracked medicine receipt / When user attempts to post without batch/expiry` },
  { id: "REQ-INV-001-02", uat: "UAT-INV-001-02", status: "in product", statement: `Given a stock adjustment / When approved and posted` },
  { id: "REQ-INV-001-03", uat: "UAT-INV-001-03", status: "in product", statement: `Given multiple stock locations / When location filter changes` },
  { id: "REQ-INV-001-04", uat: "UAT-INV-001-04", status: "in product", statement: `Given a stock movement is posted / When item history is opened` },
  { id: "REQ-INV-002-01", uat: "UAT-INV-002-01", status: "in product", statement: `Given stock falls below configured threshold / When balance recalculates` },
  { id: "REQ-INV-002-02", uat: "UAT-INV-002-02", status: "in product", statement: `Given a batch enters the configured expiry window / When scheduled evaluation runs` },
  { id: "REQ-INV-002-03", uat: "UAT-INV-002-03", status: "in product", statement: `Given underlying stock is replenished / When balance rises above threshold` },
  { id: "REQ-INV-002-04", uat: "UAT-INV-002-04", status: "in product", statement: `Given an alert creates a replenishment request / When viewed later` },
  { id: "REQ-BIL-001-01", uat: "UAT-BIL-001-01", status: "in product", statement: `Given a completed encounter with billable lines, the user can create one draft invoice without duplicating source charges.` },
  { id: "REQ-BIL-001-02", uat: "UAT-BIL-001-02", status: "in product", statement: `When an invoice is issued, its identifier and issued line values are frozen.` },
  { id: "REQ-BIL-001-03", uat: "UAT-BIL-001-03", status: "in product", statement: `When payer type is Insurance, required payer/policy fields are enforced before issue.` },
  { id: "REQ-BIL-001-04", uat: "UAT-BIL-001-04", status: "in product", statement: `The generated invoice contains patient/encounter/payer references and itemized services.` },
  { id: "REQ-BIL-002-01", uat: "UAT-BIL-002-01", status: "in product", statement: `Posting a valid partial payment updates invoice status to Part-paid and recalculates outstanding once.` },
  { id: "REQ-BIL-002-02", uat: "UAT-BIL-002-02", status: "in product", statement: `A full valid payment sets outstanding to zero and invoice status to Paid.` },
  { id: "REQ-BIL-002-03", uat: "UAT-BIL-002-03", status: "in product", statement: `A reversal creates a separate compensating transaction with reason and approver.` },
  { id: "REQ-BIL-002-04", uat: "UAT-BIL-002-04", status: "in product", statement: `Payment export/receipt displays transaction reference and responsible payer.` },
  { id: "REQ-INS-001-01", uat: "UAT-INS-001-01", status: "in product", statement: `Dashboard counts reconcile to filtered claim records by status.` },
  { id: "REQ-INS-001-02", uat: "UAT-INS-001-02", status: "in product", statement: `Opening a claim loads the same Claim ID and linked patient/invoice context.` },
  { id: "REQ-INS-001-03", uat: "UAT-INS-001-03", status: "in product", statement: `Users only see claims for their authorized entities/hotels.` },
  { id: "REQ-INS-001-04", uat: "UAT-INS-001-04", status: "in product", statement: `Sensitive exports create an audit entry.` },
  { id: "REQ-INS-002-01", uat: "UAT-INS-002-01", status: "in product", statement: `When a policy is verified, user, method, date/time and evidence/reference are retained.` },
  { id: "REQ-INS-002-02", uat: "UAT-INS-002-02", status: "in product", statement: `Expired/out-of-date policy triggers warning or block according to rule.` },
  { id: "REQ-INS-002-03", uat: "UAT-INS-002-03", status: "in product", statement: `Changing verification status creates history.` },
  { id: "REQ-INS-002-04", uat: "UAT-INS-002-04", status: "in product", statement: `Claim readiness can consume current coverage status.` },
  { id: "REQ-INS-003-01", uat: "UAT-INS-003-01", status: "in product", statement: `A draft claim can be created only from an eligible invoice/encounter for the same patient.` },
  { id: "REQ-INS-003-02", uat: "UAT-INS-003-02", status: "in product", statement: `Submitting a Ready claim stamps user/time/channel and freezes that submission version.` },
  { id: "REQ-INS-003-03", uat: "UAT-INS-003-03", status: "in product", statement: `Required attachments are evaluated from the payer ruleset.` },
  { id: "REQ-INS-003-04", uat: "UAT-INS-003-04", status: "in product", statement: `Claim amount reconciles with invoice, patient share and payer allocation.` },
  { id: "REQ-INS-004-01", uat: "UAT-INS-004-01", status: "in product", statement: `Every claim status update creates a timestamped history event and preserves the prior state.` },
  { id: "REQ-INS-004-02", uat: "UAT-INS-004-02", status: "in product", statement: `A claim cannot be marked Paid without linked settlement.` },
  { id: "REQ-INS-004-03", uat: "UAT-INS-004-03", status: "in product", statement: `Partial approval/payment displays claimed, approved, paid and outstanding separately.` },
  { id: "REQ-INS-004-04", uat: "UAT-INS-004-04", status: "in product", statement: `Resubmission preserves the original submitted package/version.` },
  { id: "REQ-INS-005-01", uat: "UAT-INS-005-01", status: "in product", statement: `Running readiness on the same unchanged claim/ruleset returns the same result.` },
  { id: "REQ-INS-005-02", uat: "UAT-INS-005-02", status: "in product", statement: `Each missing mandatory requirement is displayed with remediation target.` },
  { id: "REQ-INS-005-03", uat: "UAT-INS-005-03", status: "in product", statement: `Readiness stores evaluation date/time and ruleset version.` },
  { id: "REQ-INS-005-04", uat: "UAT-INS-005-04", status: "in product", statement: `Any override records approver, reason and failed checks.` },
  { id: "REQ-CRM-001-01", uat: "UAT-CRM-001-01", status: "in product", statement: `Authorized user can perform the core purpose of Hotel Partner Profile / 360 View as defined in the Detailed FRD.` },
  { id: "REQ-CRM-002-01", uat: "UAT-CRM-002-01", status: "in product", statement: `Authorized user can create a hotel/room medical service request with hotel, room/guest context, service type and priority.` },
  { id: "REQ-CRM-002-02", uat: "UAT-CRM-002-02", status: "in product", statement: `A service request can be assigned/reassigned to an authorized provider without losing history.` },
  { id: "REQ-CRM-002-03", uat: "UAT-CRM-002-03", status: "in product", statement: `When the request becomes a clinical visit, it links to the patient/encounter rather than creating a duplicate patient identity.` },
  { id: "REQ-CRM-002-04", uat: "UAT-CRM-002-04", status: "in product", statement: `Emergency/ambulance request follows escalation rules.` },
  { id: "REQ-CRM-003-01", uat: "UAT-CRM-003-01", status: "in product", statement: `Authorized operations users can view hotel requests scoped to assigned entities.` },
  { id: "REQ-CRM-003-02", uat: "UAT-CRM-003-02", status: "in product", statement: `Status transitions follow the configured request lifecycle.` },
  { id: "REQ-CRM-003-03", uat: "UAT-CRM-003-03", status: "in product", statement: `Overdue requests trigger configured alerts/escalations.` },
  { id: "REQ-CRM-003-04", uat: "UAT-CRM-003-04", status: "in product", statement: `Completed request remains historically searchable.` },
  { id: "REQ-CRM-004-01", uat: "UAT-CRM-004-01", status: "in product", statement: `Authorized hotel user can access only their property scope.` },
  { id: "REQ-CRM-004-02", uat: "UAT-CRM-004-02", status: "in product", statement: `Portal exposes agreed operational reports, requests and documents without unnecessary clinical detail.` },
  { id: "REQ-CRM-004-03", uat: "UAT-CRM-004-03", status: "in product", statement: `Hotel user can create/track service requests where enabled.` },
  { id: "REQ-CRM-004-04", uat: "UAT-CRM-004-04", status: "in product", statement: `Shared documents/reports are versioned and downloadable according to permission.` },
  { id: "REQ-QLT-001-01", uat: "UAT-QLT-001-01", status: "in product", statement: `Authorized user can create and submit feedback linked to the correct hotel/encounter.` },
  { id: "REQ-QLT-001-02", uat: "UAT-QLT-001-02", status: "in product", statement: `Survey scoring follows the active template version.` },
  { id: "REQ-QLT-001-03", uat: "UAT-QLT-001-03", status: "in product", statement: `Anonymous response does not expose direct identifiers to normal quality users.` },
  { id: "REQ-QLT-001-04", uat: "UAT-QLT-001-04", status: "in product", statement: `Low-score threshold triggers configured follow-up workflow.` },
  { id: "REQ-QLT-001-05", uat: "UAT-QLT-001-05", status: "in product", statement: `Publication consent is enforced.` },
  { id: "REQ-QLT-002-01", uat: "UAT-QLT-002-01", status: "in product", statement: `New incident can be created with mandatory fields.` },
  { id: "REQ-QLT-002-02", uat: "UAT-QLT-002-02", status: "in product", statement: `Severity drives configured escalation.` },
  { id: "REQ-QLT-002-03", uat: "UAT-QLT-002-03", status: "in product", statement: `CAPA cannot close without required evidence.` },
  { id: "REQ-QLT-002-04", uat: "UAT-QLT-002-04", status: "in product", statement: `Reopening a closed incident preserves prior history.` },
  { id: "REQ-RPT-001-01", uat: "UAT-RPT-001-01", status: "in product", statement: `Dashboard totals reconcile with source transactions for same filters.` },
  { id: "REQ-RPT-001-02", uat: "UAT-RPT-001-02", status: "in product", statement: `Changing date/entity filters recalculates all cards and charts.` },
  { id: "REQ-RPT-001-03", uat: "UAT-RPT-001-03", status: "in product", statement: `User cannot drill into unauthorized entity or patient detail.` },
  { id: "REQ-RPT-001-04", uat: "UAT-RPT-001-04", status: "in product", statement: `Export reproduces active filter context.` },
  { id: "REQ-RPT-002-01", uat: "UAT-RPT-002-01", status: "in product", statement: `Report can be generated for one hotel/month using approved definitions.` },
  { id: "REQ-RPT-002-02", uat: "UAT-RPT-002-02", status: "in product", statement: `Hotel user cannot access another property report.` },
  { id: "REQ-RPT-002-03", uat: "UAT-RPT-002-03", status: "in product", statement: `Published report is version locked.` },
  { id: "REQ-RPT-002-04", uat: "UAT-RPT-002-04", status: "in product", statement: `PDF contains no direct patient identifiers in standard partner report.` },
  { id: "REQ-RPT-003-01", uat: "UAT-RPT-003-01", status: "in product", statement: `Billed/collected/outstanding reconcile to transaction records.` },
  { id: "REQ-RPT-003-02", uat: "UAT-RPT-003-02", status: "in product", statement: `Claim receivable does not double count paid or rejected amounts.` },
  { id: "REQ-RPT-003-03", uat: "UAT-RPT-003-03", status: "in product", statement: `Currency filter/consolidation is transparent.` },
  { id: "REQ-RPT-003-04", uat: "UAT-RPT-003-04", status: "in product", statement: `Unauthorized users cannot access payment-level detail.` },
  { id: "REQ-MGT-001-01", uat: "UAT-MGT-001-01", status: "in product", statement: `Executive totals reconcile to source module dashboards.` },
  { id: "REQ-MGT-001-02", uat: "UAT-MGT-001-02", status: "in product", statement: `Restricted clinical detail is not exposed to finance/investor-only roles.` },
  { id: "REQ-MGT-001-03", uat: "UAT-MGT-001-03", status: "in product", statement: `Alerts are actionable and scoped.` },
  { id: "REQ-MGT-001-04", uat: "UAT-MGT-001-04", status: "in product", statement: `Stale data is visible.` },
  { id: "REQ-ADM-001-01", uat: "UAT-ADM-001-01", status: "in product", statement: `Admin can create an account with valid role and entity scope.` },
  { id: "REQ-ADM-001-02", uat: "UAT-ADM-001-02", status: "in product", statement: `Deactivated user cannot start a new authorized session.` },
  { id: "REQ-ADM-001-03", uat: "UAT-ADM-001-03", status: "in product", statement: `Historical records retain original user attribution after deactivation.` },
  { id: "REQ-ADM-001-04", uat: "UAT-ADM-001-04", status: "in product", statement: `Unauthorized admin cannot grant a higher privileged role.` },
  { id: "REQ-ADM-002-01", uat: "UAT-ADM-002-01", status: "in product", statement: `Configured role blocks actions marked No Access.` },
  { id: "REQ-ADM-002-02", uat: "UAT-ADM-002-02", status: "in product", statement: `Entity-scoped role cannot read another hotel/clinic.` },
  { id: "REQ-ADM-002-03", uat: "UAT-ADM-002-03", status: "in product", statement: `Permission version change is traceable.` },
  { id: "REQ-ADM-002-04", uat: "UAT-ADM-002-04", status: "in product", statement: `Exported matrix reflects effective active policy.` },
  { id: "REQ-ADM-003-01", uat: "UAT-ADM-003-01", status: "in product", statement: `Create/update/approve/export actions generate audit events.` },
  { id: "REQ-ADM-003-02", uat: "UAT-ADM-003-02", status: "in product", statement: `Normal admin cannot edit/delete audit event.` },
  { id: "REQ-ADM-003-03", uat: "UAT-ADM-003-03", status: "in product", statement: `Sensitive values are masked.` },
  { id: "REQ-ADM-003-04", uat: "UAT-ADM-003-04", status: "in product", statement: `Entity restrictions still apply when navigating from audit to record.` },
  { id: "REQ-ADM-004-01", uat: "UAT-ADM-004-01", status: "in product", statement: `Valid configuration can be activated and takes effect on/after effective date.` },
  { id: "REQ-ADM-004-02", uat: "UAT-ADM-004-02", status: "in product", statement: `Historical transaction retains traceability to relevant configuration/version.` },
  { id: "REQ-ADM-004-03", uat: "UAT-ADM-004-03", status: "in product", statement: `Invalid/dependent configuration cannot activate.` },
  { id: "REQ-ADM-004-04", uat: "UAT-ADM-004-04", status: "in product", statement: `Critical configuration change follows approval policy.` },
  { id: "REQ-ADM-005-01", uat: "UAT-ADM-005-01", status: "in product", statement: `New master record becomes selectable only when valid and Active.` },
  { id: "REQ-ADM-005-02", uat: "UAT-ADM-005-02", status: "in product", statement: `Used record cannot be hard deleted.` },
  { id: "REQ-ADM-005-03", uat: "UAT-ADM-005-03", status: "in product", statement: `Duplicate code is rejected.` },
  { id: "REQ-ADM-005-04", uat: "UAT-ADM-005-04", status: "in product", statement: `Bulk import returns row-level outcome.` },
  { id: "REQ-REF-001-01", uat: "UAT-REF-001-01", status: "in product", statement: `A clinician can submit a referral with the mandatory fields.` },
  { id: "REQ-REF-001-02", uat: "UAT-REF-001-02", status: "in product", statement: `An ambulance request links one transfer to the referral.` },
  { id: "REQ-REF-001-03", uat: "UAT-REF-001-03", status: "in product", statement: `The referral letter carries identity, stay, destination, priority and clinical summary.` },
  { id: "REQ-REF-001-04", uat: "UAT-REF-001-04", status: "in product", statement: `Destination, priority and status changes stay in the audit history.` },
  { id: "REQ-REF-001-05", uat: "UAT-REF-001-05", status: "in product", statement: `A non-clinical role cannot edit the referral content.` },
  { id: "REQ-REF-002-01", uat: "UAT-REF-002-01", status: "in product", statement: `Requesting an ambulance creates one linked transfer.` },
  { id: "REQ-REF-002-02", uat: "UAT-REF-002-02", status: "in product", statement: `The transfer moves through assignment, travel, arrival, handover and closure.` },
  { id: "REQ-REF-002-03", uat: "UAT-REF-002-03", status: "in product", statement: `The transfer cannot skip a step in the journey.` },
  { id: "REQ-REF-002-04", uat: "UAT-REF-002-04", status: "in product", statement: `Transport risks stay visible on the transfer before departure.` },
  { id: "REQ-REF-002-05", uat: "UAT-REF-002-05", status: "in product", statement: `Closure requires receiving-facility handover evidence.` },
  { id: "REQ-REF-003-01", uat: "UAT-REF-003-01", status: "in product", statement: `Referral and transfer history stay on one record.` },
  { id: "REQ-REF-003-02", uat: "UAT-REF-003-02", status: "in product", statement: `The status shown is the latest valid step.` },
  { id: "REQ-REF-003-03", uat: "UAT-REF-003-03", status: "in product", statement: `Documents from the transfer are available from the visit pack.` },
  { id: "REQ-REF-003-04", uat: "UAT-REF-003-04", status: "in product", statement: `Transfer closure is recorded separately from the encounter.` },
  { id: "REQ-REF-003-05", uat: "UAT-REF-003-05", status: "in product", statement: `Closed transfers remain searchable.` },
];
